### ISSUE TITLE
Port mozilla-cloud-services-logger here

### ISSUE THREAD

**Issue by jezdez** [mozilla-services/python-dockerflow#2]
There is already a package called https://github.com/mozilla/mozilla-cloud-services-logger by @lmorchard that implements two things:

1. A Python logging formatter consistent with [mozlog](https://github.com/mozilla-services/Dockerflow/blob/master/docs/mozlog.md)

2. A Django middleware that emits up [request.summary](https://github.com/mozilla-services/Dockerflow/blob/master/docs/mozlog.md#application-request-summary-type-requestsummary) following the Dockerflow specs

Both are essential to follow Docker and should live in a generic purpose library like python-dockerflow to allow a "one stop shop" experience for Dockerflow users.

@lmorchard Are you okay with us porting over your code into this repo?

**Comment by lmorchard** [comment]
I'm more than okay! We switched to static site rendering on the project that was using this, so it's effectively unmaintained right now

**Comment by jezdez** [comment]
@lmorchard Awesome! Do you want me to add you to the dockerflow team, too?
