### ISSUE TITLE
Django 2.0 Support

### ISSUE THREAD

**Issue by jaredkerim** [mozilla-services/python-dockerflow#22]
From my attempt to update to Django 2.0:

  File "/usr/local/lib/python3.6/site-packages/dockerflow/django/middleware.py", line 52, in _build_extra_meta
    out['uid'] = (request.user.is_authenticated() and
TypeError: 'bool' object is not callable

**Comment by jezdez** [comment]
Good catch, `is_authenticated` became a property so we'll need to add a version check and use `request.user.is_authenticated` instead.

BTW, 2.0 should not be used for Mozilla projects for now since it's not an LTS release :)

**Comment by jaredkerim** [comment]
You are correct! I am using an old version, disregard this!

**Comment by jezdez** [comment]
Yay!
