### ISSUE TITLE
Log query strings

### ISSUE THREAD

**Issue by jvehent** [mozilla-services/python-dockerflow#44]
[Related discussion](https://matrix.to/#/!UAkBBnGDgtvizoVKrC:mozilla.org/$IHuNXHksBrsR2QwBtS_NMUejg2i3rnYFZ77E7gk3jQA?via=mozilla.org&via=matrix.org&via=hackers.town)

It is [possible ](https://github.com/mozilla-services/dependency-observatory/pull/200/files) to override the `summary_extra` method to log query strings, but it feels a bit hackish and would look much cleaner as a feature of the library hidden behind a config option.

**Comment by leplatrem** [comment]
Fixed in #97
