### ISSUE TITLE
access request id in Flask view?

### ISSUE THREAD

**Issue by g-k** [mozilla-services/python-dockerflow#50]
I want to include the request ID to add to error messages for bug reports from a flask app.

In a Flask view, is `g._request_id` the best way to access the request ID or is there a public property or method to access it?

**Comment by jezdez** [comment]
Yeah, `g._request_id` is safe to use and we can just add a non-pseudo-private attribute to the `g` thread local. Mind opening a PR that stays backward-compatible?
