### ISSUE TITLE
Default checks in Django 3.2 break in dockerflow-python

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla-services/python-dockerflow#56]
[Experimenter](https://github.com/mozilla/experimenter) just updated to Django 3.2 and discovered this:

https://code.djangoproject.com/ticket/32665#ticket

In the heartbeat endpoint, we run the check and then optionally silence its output if it's in the silenced outputs:

https://github.com/mozilla-services/python-dockerflow/blob/main/src/dockerflow/django/views.py#L72-L73

but because the check throws altogether, this causes the heartbeat to 500.  Perhaps we should do that in the opposite order?

**Comment by jezdez** [comment]
For the record, I'm not at Mozilla anymore, so best is to ping the @mozilla-services/dockerflow team

**Comment by djmitche** [comment]
Would it be better to catch exceptions from checks and treat those as failures?  Then such issues would be surfaced properly even if they're not silenced.

**Comment by jaredlockhart** [comment]
@djmitche Yeah that's also an option, I think I'd just like to be able to silence it, one way or the other.

**Comment by djmitche** [comment]
So, it can't be silenced before it's checked, since the silencing is done by `id`.  I think the upstream bug will need to be fixed.

**Comment by jaredlockhart** [comment]
Sounds good I'll close this then.
