### ISSUE TITLE
New release with django 4 support

### ISSUE THREAD

**Issue by lunika** [mozilla-services/python-dockerflow#65]
Hi,

Is it possible to publish a new release on pypi with the django 4 support ? You merged its support with PR #62 

Thanks

**Comment by diox** [comment]
Hi,

I just released 2022.1.0:
- https://github.com/mozilla-services/python-dockerflow/tree/2022.1.0
- https://pypi.org/project/dockerflow/#history

**Comment by lunika** [comment]
Thanks :pray:
