### ISSUE TITLE
RemovedInDjango41Warning for default_app_config

### ISSUE THREAD

**Issue by willkg** [mozilla-services/python-dockerflow#66]
dockerflow kicks up a RemovedInDjango41Warning because there's a `default_app_config` defined in `dockerflow.django.__init__.py`. 

As of 3.2, Django automatically finds `AppConfig` things:

https://docs.djangoproject.com/en/3.2/releases/3.2/#automatic-appconfig-discovery

Further, as of 3.2 setting `default_app_config` is deprecated:

https://docs.djangoproject.com/en/3.2/releases/3.2/#id3

**Comment by jwhitlock** [comment]
Fixed in PR #67
