### ISSUE TITLE
dockerflow.logging.JsonLogFormatter doesn't handle extra arguments that are not json-serializable

### ISSUE THREAD

**Issue by diox** [mozilla-services/python-dockerflow#8]
Enabling `dockerflow.logging.JsonLogFormatter` in your project can cause `TypeError` exceptions when extra, non json-serializable arguments are passed to the logging call.

```python
>>> from logging import getLogger
>>> getLogger('foo').warning('warning with extra info', extra={'something': object()})
Traceback (most recent call last):
(...)
TypeError: <object object at 0x7f5e88a54630> is not JSON serializable
```

It's a perfect valid logging call, you might have other formatters configured taking advantage of the extra data. Django does that in some of its core, for instance [passing `request` objects when logging 404 or 500 request errors](https://docs.djangoproject.com/en/1.10/topics/logging/#django-request).

I think the best approach here would be to have a custom serializer class that would just use `repr()` on data it can not serialize.

**Comment by jezdez** [comment]
Yikes, that's a good call! I'm not sure if we should go a step further and use Django's datetime aware (and others) JSONEncoder subclass. But I'm happy to try things out with the repr first.

**Comment by diox** [comment]
That's a good point. I was so focused on avoiding the exception that I didn't think about that. I'll file a new issue.
